-- =============================================================================
-- 0009_auth_tokens.sql — refresh / reset / email-verification tokens + email
-- -----------------------------------------------------------------------------
-- MIGRATION (run once on an EXISTING database — `laetoli-data migrate`). Also
-- mirrored into db/init/02_auth.sql with the same definitions so a FRESH boot
-- gets them too. Idempotent: CREATE ... IF NOT EXISTS, ADD COLUMN IF NOT EXISTS,
-- CREATE INDEX IF NOT EXISTS, CREATE OR REPLACE, naturally re-runnable GRANTs.
--
-- WHAT THIS ADDS — the day-to-day account machinery on top of auth.users:
--   * auth.users.email (optional, unique-when-present) + email_verified.
--   * auth.refresh_tokens — opaque ROTATING refresh tokens (sha256-hashed).
--       A `family_id` chains a rotation lineage; presenting an already-revoked
--       token is treated as reuse and the auth service revokes the whole family.
--   * auth.reset_tokens — single-use, short-lived password-reset tokens.
--   * auth.email_verification_tokens — single-use, short-lived verify tokens.
--   * auth.cleanup_expired_tokens() — housekeeping (schedule nightly).
--
-- SECURITY
--   * Token VALUES are crypto.randomBytes generated by the auth service and are
--     NEVER stored — only their SHA-256 digest (token_hash) is persisted. A DB
--     leak therefore yields no usable tokens. Lookups hash the presented value
--     and compare in constant time (in the Node service).
--   * Only the laetoli_auth service role gets write access (grants below). These
--     tables are NEVER exposed through PostgREST.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()

-- --- auth.users: optional email + verification flag --------------------------
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS email          text;
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS email_verified boolean NOT NULL DEFAULT false;

-- Unique only WHEN PRESENT (partial index) — username/anon accounts have NULL.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique
  ON auth.users (email) WHERE email IS NOT NULL;

COMMENT ON COLUMN auth.users.email          IS 'Optional contact email; unique when present.';
COMMENT ON COLUMN auth.users.email_verified IS 'true once the email has been confirmed.';

-- --- auth.refresh_tokens (rotating, hashed at rest) --------------------------
CREATE TABLE IF NOT EXISTS auth.refresh_tokens (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text        NOT NULL UNIQUE,
  family_id  uuid        NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_agent text
);
COMMENT ON TABLE auth.refresh_tokens IS
  'Opaque rotating refresh tokens (sha256-hashed). A family_id ties a rotation '
  'chain together so reuse of a revoked token can revoke the whole family.';
CREATE INDEX IF NOT EXISTS refresh_tokens_user_idx   ON auth.refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS refresh_tokens_family_idx ON auth.refresh_tokens (family_id);
CREATE INDEX IF NOT EXISTS refresh_tokens_expiry_idx ON auth.refresh_tokens (expires_at);

-- --- auth.reset_tokens (single-use password reset) --------------------------
CREATE TABLE IF NOT EXISTS auth.reset_tokens (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text        NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE auth.reset_tokens IS
  'Single-use, short-lived password-reset tokens (sha256-hashed).';
CREATE INDEX IF NOT EXISTS reset_tokens_user_idx   ON auth.reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS reset_tokens_expiry_idx ON auth.reset_tokens (expires_at);

-- --- auth.email_verification_tokens (single-use email verify) ---------------
CREATE TABLE IF NOT EXISTS auth.email_verification_tokens (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token_hash text        NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE auth.email_verification_tokens IS
  'Single-use, short-lived email-verification tokens (sha256-hashed).';
CREATE INDEX IF NOT EXISTS email_verification_tokens_user_idx
  ON auth.email_verification_tokens (user_id);
CREATE INDEX IF NOT EXISTS email_verification_tokens_expiry_idx
  ON auth.email_verification_tokens (expires_at);

-- --- cleanup helper -----------------------------------------------------------
CREATE OR REPLACE FUNCTION auth.cleanup_expired_tokens()
RETURNS void
LANGUAGE sql
AS $$
  DELETE FROM auth.refresh_tokens
    WHERE expires_at < now() OR revoked_at < now() - interval '7 days';
  DELETE FROM auth.reset_tokens
    WHERE expires_at < now() OR used_at IS NOT NULL;
  DELETE FROM auth.email_verification_tokens
    WHERE expires_at < now() OR used_at IS NOT NULL;
$$;
COMMENT ON FUNCTION auth.cleanup_expired_tokens() IS
  'Deletes expired/consumed auth tokens. Schedule nightly via scheduler.jobs.';

-- --- grants -------------------------------------------------------------------
-- Only the auth service role writes these; never exposed through PostgREST.
GRANT SELECT, INSERT, UPDATE, DELETE ON auth.refresh_tokens             TO laetoli_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON auth.reset_tokens               TO laetoli_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON auth.email_verification_tokens  TO laetoli_auth;
GRANT EXECUTE ON FUNCTION auth.cleanup_expired_tokens() TO laetoli_auth;

GRANT ALL ON ALL TABLES IN SCHEMA auth TO laetoli_admin;

-- =============================================================================
-- ADMIN RECOVERY PATH (operator-triggered reset for a locked-out user):
--   The auth service has no privileged admin endpoint by design. An operator
--   recovers a user directly in SQL (run AS laetoli_auth / laetoli_admin):
--
--   -- 1) Issue a reset the operator can hand to the user out-of-band. Generate
--   --    a random value APP-side, store ONLY its sha256, share the plaintext:
--   --      value = base64url(randomBytes(32)); store encode(digest(value,'sha256'),'hex')
--   INSERT INTO auth.reset_tokens (user_id, token_hash, expires_at)
--   SELECT id, '<sha256-hex-of-the-random-value>', now() + interval '1 hour'
--   FROM auth.users WHERE username = '<the_locked_user>';
--   --    Then the user POSTs {token,password} to /password/reset as normal.
--
--   -- OR 2) Hard recovery — set a known bcrypt hash directly and force re-login:
--   UPDATE auth.users SET password_hash = '<bcrypt-hash>' WHERE username = '<u>';
--   UPDATE auth.refresh_tokens SET revoked_at = now()
--     WHERE user_id = (SELECT id FROM auth.users WHERE username = '<u>')
--       AND revoked_at IS NULL;
-- =============================================================================
