-- =============================================================================
-- 0011_phone_otp.sql — sovereign phone-OTP login codes
-- -----------------------------------------------------------------------------
-- MIGRATION (run once on an EXISTING database — `laetoli-data migrate`). Also
-- mirrored into db/init/02_auth.sql with the same definitions so a FRESH boot
-- gets it too. Idempotent: CREATE ... IF NOT EXISTS, CREATE INDEX IF NOT EXISTS,
-- CREATE OR REPLACE, naturally re-runnable GRANTs.
--
-- WHAT THIS ADDS — passwordless phone login via a 6-digit SMS code:
--   * auth.users.phone (optional, unique-when-present) — the OTP identity.
--   * auth.otp_codes — short-lived, sha256-HASHED OTP codes with an attempt
--       counter so brute force is bounded. POST /otp/request issues + texts a
--       code; POST /otp/verify checks hash+expiry+attempts and, on success,
--       issues the normal access + refresh tokens (exactly like login).
--
-- SECURITY
--   * The 6-digit code is generated by the auth service and is NEVER stored —
--     only its SHA-256 digest (code_hash) is persisted. Lookups hash the
--     presented code and compare in constant time (in the Node service).
--   * `attempts` caps wrong guesses; the row is consumed (used_at) on success.
--   * Only the laetoli_auth service role gets write access (grants below). This
--     table is NEVER exposed through PostgREST.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()

-- --- auth.users: optional phone (the OTP identity) ---------------------------
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS phone text;

-- Unique only WHEN PRESENT (partial index) — most accounts have NULL phone.
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_unique
  ON auth.users (phone) WHERE phone IS NOT NULL;

COMMENT ON COLUMN auth.users.phone IS 'Optional phone (E.164); unique when present. Used for SMS-OTP login.';

-- --- auth.otp_codes (single-use, hashed, attempt-limited) --------------------
CREATE TABLE IF NOT EXISTS auth.otp_codes (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  phone      text        NOT NULL,
  code_hash  text        NOT NULL,
  expires_at timestamptz NOT NULL,
  attempts   integer     NOT NULL DEFAULT 0,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE auth.otp_codes IS
  'Single-use, short-lived phone-OTP codes (sha256-hashed). attempts caps brute '
  'force; used_at marks consumption. Never exposed through PostgREST.';
CREATE INDEX IF NOT EXISTS otp_codes_phone_idx  ON auth.otp_codes (phone);
CREATE INDEX IF NOT EXISTS otp_codes_user_idx   ON auth.otp_codes (user_id);
CREATE INDEX IF NOT EXISTS otp_codes_expiry_idx ON auth.otp_codes (expires_at);

-- --- cleanup: fold expired/used OTP rows into the existing housekeeping -------
CREATE OR REPLACE FUNCTION auth.cleanup_expired_tokens()
RETURNS void
LANGUAGE sql
AS $$
  DELETE FROM auth.refresh_tokens
    WHERE expires_at < now() OR revoked_at < now() - interval '7 days';
  DELETE FROM auth.reset_tokens
    WHERE expires_at < now() OR used_at IS NOT NULL;
  DELETE FROM auth.email_verification_tokens
    WHERE expires_at < now() OR used_at IS NOT NULL;
  DELETE FROM auth.otp_codes
    WHERE expires_at < now() OR used_at IS NOT NULL;
$$;
COMMENT ON FUNCTION auth.cleanup_expired_tokens() IS
  'Deletes expired/consumed auth tokens + OTP codes. Schedule nightly via scheduler.jobs.';

-- --- grants -------------------------------------------------------------------
-- Only the auth service role writes these; never exposed through PostgREST.
GRANT SELECT, INSERT, UPDATE, DELETE ON auth.otp_codes TO laetoli_auth;

GRANT ALL ON ALL TABLES IN SCHEMA auth TO laetoli_admin;
